# Generated by Django 5.0.4 on 2025-02-08 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Admin_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=128)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact_Information', models.CharField(max_length=255)),
                ('Admin_Role', models.CharField(max_length=100)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('Hostel_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Hostel_Name', models.CharField(max_length=255, unique=True)),
                ('No_Of_Rooms', models.IntegerField(default=0)),
                ('No_Of_Students', models.IntegerField(default=0)),
                ('Single_Seater_Rooms', models.IntegerField(default=0)),
                ('Two_Seater_Rooms', models.IntegerField(default=0)),
                ('Three_Seater_Rooms', models.IntegerField(default=0)),
                ('Six_Seater_Rooms', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('Mess_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Mess_Menu', models.TextField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Hostel_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('Notice_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Content', models.TextField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Expiry_Date', models.DateTimeField(blank=True, null=True)),
                ('Is_Active', models.BooleanField(default=True)),
                ('Admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Room_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Room_Type', models.CharField(max_length=255)),
                ('Capacity', models.IntegerField()),
                ('Location', models.CharField(max_length=255)),
                ('Room_No', models.CharField(max_length=50, unique=True)),
                ('Floor_No', models.IntegerField()),
                ('Students_Alloted', models.IntegerField(default=0)),
                ('Hostel_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Registration_Number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('F_Name', models.CharField(max_length=50)),
                ('L_Name', models.CharField(max_length=50)),
                ('Contact_Info', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Department', models.CharField(max_length=100)),
                ('FatherName', models.CharField(max_length=50)),
                ('fee_status', models.CharField(choices=[('NOT_PAID', 'Not Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('FULLY_PAID', 'Fully Paid')], default='NOT_PAID', max_length=20)),
                ('mess_status', models.BooleanField(default=False)),
                ('total_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Hostel_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='hostel.hostel')),
                ('Room_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='hostel.room')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Fee_Type', models.CharField(max_length=255)),
                ('Payment_Date', models.DateTimeField()),
                ('Amount_Paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Receipt_Number', models.CharField(max_length=255)),
                ('Fee_Status', models.CharField(max_length=50)),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hostel.student')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('Complaint_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Complaint_Description', models.TextField()),
                ('Complaint_Type', models.CharField(max_length=255)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
                ('Admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.admin')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('Attendance_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('Status', models.CharField(max_length=50)),
                ('Admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.admin')),
                ('Mess_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.mess')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('Visitor_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Visitor_Name', models.CharField(max_length=255)),
                ('Contact_Info', models.CharField(max_length=255)),
                ('Time_in', models.DateTimeField()),
                ('Time_out', models.DateTimeField()),
                ('Requested_By', models.CharField(max_length=255)),
                ('Approved_By', models.CharField(max_length=255)),
                ('Approval_Status', models.CharField(max_length=50)),
                ('Request_Date', models.DateTimeField()),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
        ),
    ]
