# Generated by Django 5.0.4 on 2025-02-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Due_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_Mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online'), ('CHEQUE', 'Cheque')], default='CASH', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='Voucher_No',
            field=models.CharField(blank=True, default='VOU-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Fee_Status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('PENDING', 'Pending')], default='UNPAID', max_length=50),
        ),
    ]
