# Generated by Django 5.0.4 on 2025-02-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_payment_due_date_payment_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Installment_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
