# Generated by Django 5.0.4 on 2025-02-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_payment_installment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Payment_Mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online'), ('BANK', 'Bank')], default='CASH', max_length=50),
        ),
    ]
