# Generated by Django 5.0.4 on 2025-02-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_alter_payment_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='total_fee_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='payments_pdfs/'),
        ),
    ]
