# Generated by Django 5.0.4 on 2025-02-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_paymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pdf_file',
        ),
    ]
