# Generated by Django 5.0.4 on 2025-02-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_remove_payment_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='payments_pdfs/'),
        ),
    ]
