# Generated by Django 5.0.4 on 2025-02-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_payment_pdf_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentRequest',
        ),
    ]
