# Generated by Django 5.0.4 on 2025-02-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_delete_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
