# Generated by Django 5.0.4 on 2025-02-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_alter_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
    ]
