# Generated by Django 5.0.4 on 2025-02-10 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0019_remove_admin_user_delete_noticeboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('Notice_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Content', models.TextField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Expiry_Date', models.DateTimeField(blank=True, null=True)),
                ('Is_Active', models.BooleanField(default=True)),
                ('Admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.admin')),
            ],
        ),
    ]
