# Generated by Django 5.0.4 on 2025-02-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0020_noticeboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voucher_no', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(max_length=50)),
            ],
        ),
    ]
