# Generated by Django 5.0.4 on 2025-02-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0022_delete_paymentrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticeBoard',
        ),
    ]
