# Generated by Django 5.0.4 on 2025-02-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0028_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
