# Generated by Django 5.0.4 on 2025-02-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0029_profile_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
