# Generated by Django 5.0.4 on 2025-02-13 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0030_visitors_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave')], default='ABSENT', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('Student_ID', 'Mess_ID', 'Date')},
        ),
    ]
