# Generated by Django 5.0.4 on 2025-02-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0032_messrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mess_status',
        ),
    ]
