# Generated by Django 5.0.4 on 2025-02-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0035_alter_messattendance_date_facedetectionrecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facedetectionrecord',
            name='date',
        ),
        migrations.AlterField(
            model_name='facedetectionrecord',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messattendance',
            name='date',
            field=models.DateField(),
        ),
    ]
