# Generated by Django 5.0.4 on 2025-03-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0036_remove_facedetectionrecord_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='Approval_Status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='Approved_By',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='Request_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
