# Generated by Django 5.0.4 on 2025-03-05 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0037_alter_visitors_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='Approval_Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='Request_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
