# Generated by Django 5.0.4 on 2025-03-05 05:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0038_alter_visitors_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='Approval_Status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='Approved_By',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='Request_Date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superuser', 'Superuser - Full System Access'), ('staff', 'Staff - Limited Administrative Access'), ('manager', 'Manager - Intermediate Administrative Access')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('department', models.CharField(blank=True, max_length=100)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_system', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
