# Generated by Django 5.0.4 on 2025-03-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0043_remove_visitors_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorrequest',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorrequest',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
