# Generated by Django 5.0.4 on 2025-03-06 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0044_visitorrequest_time_in_visitorrequest_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
