# Generated by Django 5.0.4 on 2025-03-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0045_alter_messattendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='Visitor_ID_Proof',
            field=models.CharField(default='meeting', help_text='ID card number or other identification', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='purpose_of_visit',
            field=models.CharField(default='meeting', max_length=255),
            preserve_default=False,
        ),
    ]
