# Generated by Django 5.0.4 on 2025-03-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0046_visitor_visitor_id_proof_visitor_purpose_of_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
