# Generated by Django 5.0.4 on 2025-03-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0048_paymentrequest_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='messmenu',
            name='meal_time',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1),
        ),
    ]
