# Generated by Django 5.0.4 on 2025-03-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0049_messmenu_meal_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messmenu',
            options={'ordering': ['date', 'meal_time']},
        ),
        migrations.AddField(
            model_name='messmenu',
            name='day',
            field=models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3),
        ),
        migrations.AddField(
            model_name='messmenu',
            name='month',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='messmenu',
            name='week_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messmenu',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='dish_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='meal_time',
            field=models.CharField(choices=[('BF', 'Breakfast'), ('MB', 'Milk Break'), ('LN', 'Lunch'), ('ET', 'Evening Tea/Squash'), ('DN', 'Dinner')], max_length=2),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddIndex(
            model_name='messmenu',
            index=models.Index(fields=['date'], name='hostel_mess_date_824a91_idx'),
        ),
        migrations.AddIndex(
            model_name='messmenu',
            index=models.Index(fields=['meal_time'], name='hostel_mess_meal_ti_e1c7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='messmenu',
            index=models.Index(fields=['month', 'year'], name='hostel_mess_month_2fb305_idx'),
        ),
    ]
