# Generated by Django 5.0.4 on 2025-03-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0050_alter_messmenu_options_messmenu_day_messmenu_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmenu',
            name='meal_time',
            field=models.CharField(choices=[('BF', 'Breakfast'), ('LN', 'Lunch'), ('ET', 'Evening Tea/Squash'), ('DN', 'Dinner')], max_length=2),
        ),
    ]
