# Generated by Django 5.0.4 on 2025-03-14 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0052_messmembership_approved_messmembership_date_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Hostel_ID',
        ),
        migrations.AlterField(
            model_name='messmembership',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messmembership',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='Room_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.room'),
        ),
    ]
