# Generated by Django 5.0.4 on 2025-03-17 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0053_remove_student_hostel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Hostel_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.hostel'),
        ),
    ]
