# Generated by Django 5.0.4 on 2025-03-20 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0054_student_hostel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseNotice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('NOISE', 'Noise Disturbance'), ('PROPERTY_DAMAGE', 'Property Damage'), ('CURFEW', 'Curfew Violation'), ('UNAUTHORIZED_GUEST', 'Unauthorized Guest'), ('ALCOHOL', 'Alcohol Possession'), ('SMOKING', 'Smoking in Restricted Areas'), ('RAGGING', 'Ragging'), ('OTHERS', 'Other Violations')], max_length=50)),
                ('description', models.TextField()),
                ('incident_date', models.DateTimeField()),
                ('notice_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('APPEALED', 'Appealed')], default='PENDING', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('student_response', models.TextField(blank=True, null=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='showcase_notices/evidence/')),
                ('is_read', models.BooleanField(default=False)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.admin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_notices', to='hostel.student')),
            ],
        ),
    ]
