# Generated by Django 5.0.4 on 2025-03-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0055_showcasenotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='messmembership',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='messmembership',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
