# Generated by Django 5.0.4 on 2025-04-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0056_messmembership_department_messmembership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messattendance',
            name='meal_time',
            field=models.CharField(choices=[('BF', 'Breakfast'), ('LN', 'Lunch'), ('ET', 'Evening Tea/Squash'), ('DN', 'Dinner')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messattendance',
            name='price_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='messbill',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
