# Generated by Django 5.0.4 on 2025-04-03 04:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0057_messattendance_meal_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcasenotice',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='showcasenotice',
            name='incident_date',
        ),
        migrations.RemoveField(
            model_name='showcasenotice',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='showcasenotice',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='showcasenotice',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='showcasenotice',
            name='notice_date',
        ),
        migrations.RemoveField(
            model_name='showcasenotice',
            name='notice_id',
        ),
        migrations.RemoveField(
            model_name='showcasenotice',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='showcasenotice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='showcasenotice',
            name='student',
        ),
        migrations.RemoveField(
            model_name='showcasenotice',
            name='student_response',
        ),
        migrations.RemoveField(
            model_name='showcasenotice',
            name='violation_type',
        ),
        migrations.AddField(
            model_name='showcasenotice',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_showcase_notices', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showcasenotice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='showcasenotice',
            name='id',
            field=models.BigAutoField(auto_created=True, default=124, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showcasenotice',
            name='notice_type',
            field=models.CharField(choices=[('noise', 'Noise Complaint'), ('fine', 'Fine'), ('damage', 'Property Damage'), ('conduct', 'Misconduct'), ('other', 'Other')], default=0.0006584362139917695, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showcasenotice',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showcasenotice',
            name='title',
            field=models.CharField(default='Other', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showcasenotice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showcasenotice',
            name='fine_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='StudentShowcaseNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.showcasenotice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
            options={
                'unique_together': {('student', 'notice')},
            },
        ),
        migrations.AddField(
            model_name='showcasenotice',
            name='students',
            field=models.ManyToManyField(related_name='showcase_notices', through='hostel.StudentShowcaseNotice', to='hostel.student'),
        ),
    ]
