# Generated by Django 5.0.4 on 2025-04-03 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0058_remove_showcasenotice_evidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Room_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='hostel.room'),
        ),
    ]
