# Generated by Django 5.0.4 on 2025-04-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0059_alter_student_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasenotice',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
