# Generated by Django 5.0.4 on 2025-04-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0060_alter_showcasenotice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasenotice',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
