# Generated by Django 5.0.4 on 2025-04-08 04:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0062_messrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='messbill',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MessPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('AUTO', 'Automatic Payment'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('payment_note', models.CharField(blank=True, max_length=255, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hostel.messbill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
        ),
    ]
