# Generated by Django 5.0.4 on 2025-04-08 04:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0063_messbill_payment_date_messpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='messpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('ADMIN', 'Admin Approved'), ('OTHER', 'Other')], default='CASH', max_length=10),
        ),
        migrations.CreateModel(
            name='MessPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('request_note', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_note', models.CharField(blank=True, max_length=255, null=True)),
                ('milestone_days', models.IntegerField(default=10)),
                ('bills', models.ManyToManyField(related_name='payment_requests', to='hostel.messbill')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
        ),
    ]
